###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
ininame : /home/shjo/warehouse/nifs02/isl_stable/nifs02_ini_5km_v3.nc
#grdname : /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc
grdname : /home/shjo/warehouse/nifs02/grd/roms_grd_fennel_5km_smooth_v3.nc

weight_file: /home/shjo/tmp.nc
calc_weight: True

ncformat: NETCDF3_64BIT
force_write: True

bio_model_type: npzd

flood_method_for_ini: griddata #griddata / edt / linearND

ogcm_name: /home/shjo/data/nifs02/nov/hycom/hycom_20251101_00utc.nc 

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

initdate            : 2025-11-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

vertical:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400




